[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html", "--tab-width", "4", "--html-whitespace-sensitivity", "ignore"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css", "--tab-width", "4"] }
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript", "--tab-width", "4"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript", "--tab-width", "4"] }
